- alias: DoorAlert
  initial_state: 'on'
  trigger:
     - platform: state
       entity_id: 
        - binary_sensor.voordeur
        - binary_sensor.achterdeur
       from: 'off'
       to: 'on'
  condition:
    condition: and
    conditions:
     - condition: template
       value_template: "{{ states.device_tracker.life360_tim.state != 'home' }}"
     - condition: template
       value_template: "{{ states.device_tracker.life360_hilde.state != 'home' }}"
  action:
#     - service: notify.emailth
#       data:
#        message: "Er heeft iemand de voordeur opengedaan!"
#     - service: persistent_notification.create
#       data:
#        message: "Er heeft iemand de voordeur opengedaan!"
     - service: notify.mobile_app_nokia_8_1
       data_template:
         message: "Deur geopend! -> {{ trigger.to_state.attributes.friendly_name }}"
     - service: notify.mobile_app_sm_a750fn
       data_template:
         message: "Deur geopend! -> {{ trigger.to_state.attributes.friendly_name }}"