- alias: MotionAlert
  initial_state: 'on'
  trigger:
     - platform: state
       entity_id: binary_sensor.poly_motion
       from: 'off'
       to: 'on'
     - platform: state
       entity_id: binary_sensor.keuken_motion
       from: 'off'
       to: 'on'
     - platform: state
       entity_id: binary_sensor.gang_motion
       from: 'off'
       to: 'on'
     - platform: state
       entity_id: binary_sensor.garage_motion
       from: 'off'
       to: 'on'
  condition:
    condition: and
    conditions:
     - condition: template
       value_template: "{{ states.device_tracker.life360_tim.state != 'home' }}"
     - condition: template
       value_template: "{{ states.device_tracker.life360_hilde.state != 'home' }}"
  action:
     - service: notify.mobile_app_nokia_8_1
       data_template:
         message: "Beweging in huis! -> {{ trigger.to_state.attributes.friendly_name }}"
     - service: notify.mobile_app_sm_a750fn
       data:
         message: "Beweging in huis! -> {{ trigger.to_state.attributes.friendly_name }}"

#end