- alias: WindowAlert
  initial_state: 'on'
  trigger:
     - platform: state
       entity_id: binary_sensor.living_raam_opzij
       from: 'off'
       to: 'on'
     - platform: state
       entity_id: binary_sensor.toilet_raam
       from: 'off'
       to: 'on'
     - platform: state
       entity_id: binary_sensor.poly_raam_rechts
       from: 'off'
       to: 'on'
     - platform: state
       entity_id: binary_sensor.keuken_raam_opzij
       from: 'off'
       to: 'on'
     - platform: state
       entity_id: binary_sensor.living_raam_vooraan_links
       from: 'off'
       to: 'on'
     - platform: state
       entity_id: binary_sensor.living_raam_vooraan_rechts
       from: 'off'
       to: 'on'
     - platform: state
       entity_id: binary_sensor.badkamer_raam
       from: 'off'
       to: 'on'
  condition:
    condition: and
    conditions:
     - condition: template
       value_template: "{{ states.device_tracker.life360_tim.state != 'home' }}"
     - condition: template
       value_template: "{{ states.device_tracker.life360_hilde.state != 'home' }}"
  action:
     - service: notify.mobile_app_nokia_8_1
       data_template:
         message: "Raam geopend! -> {{ trigger.to_state.attributes.friendly_name }}"
     - service: notify.mobile_app_sm_a750fn
       data_template:
         message: "Raam geopend! -> {{ trigger.to_state.attributes.friendly_name }}"
         
#end