#test
- alias: testalert
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_boolean.test
    from: 'off'
    to: 'on'
  action:
#  - service: light.turn_on
#    entity_id: 
#    - light.huiskamer_kast
#    data:
#        transition: 20
#        brightness: 255
#        kelvin: 2700
  - service: notify.mobile_app_nokia_8_1
    data:
     message: "TEST"
#  - service: notify.mobile_app_sm_a750fn
#    data:
#     message: "testbericht!"

#end