- alias: kamermarielicht_on
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kamermariedimmer
        event: 1002
  action:
  - service: light.turn_on
    entity_id:  light.kamermarielicht
#######
- alias: kamermarielicht_off
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kamermariedimmer
        event: 2002
  action:
  - service: light.turn_off
    entity_id:  light.kamermarielicht
#######
- alias: kamermarielicht_dim_up_hold
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kamermariedimmer
        event: 1001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kamermarielicht
        transition: '5'
        brightness: >
         {% set n = states.light.kamermarielicht.attributes.brightness + 20 %}
         {% if n < 255 %}
           255
         {% else %}
           {{ n }}
         {% endif %}
#######
- alias: kamermarielicht_dim_down_hold
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kamermariedimmer
        event: 2001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kamermarielicht
        transition: '5'
        brightness: >
         {% set n = states.light.kamermarielicht.attributes.brightness - 20 %}
         {% if n > 1 %}
           1
         {% else %}
           {{ n }}
         {% endif %}
#######
- alias: kamermarielicht_dim_stop_hold
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kamermariedimmer
        event: 1003
    - platform: event
      event_type: deconz_event
      event_data:
        id: kamermariedimmer
        event: 2003
  action:         
    - service: light.turn_on
      data_template:
        entity_id: light.kamermarielicht
        brightness: '{{ states.light.kamermarielicht.attributes.brightness }}'