- alias: kamerhildelicht_on
#  hide_entity: true
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kamerhildedimmer
        event: 1002
  action:
  - service: light.turn_on
    entity_id:  light.kamerhildelicht
#######
- alias: kamerhildelicht_off
#  hide_entity: true
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kamerhildedimmer
        event: 2002
  action:
  - service: light.turn_off
    entity_id:  light.kamerhildelicht
#######
- alias: kamerhildelicht_dim_up_hold
#  hide_entity: true
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kamerhildedimmer
        event: 1001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kamerhildelicht
        transition: '5'
        brightness: >
         {% set suggested = states.light.kamerhildelicht.attributes.brightness|int + 80 %}
         {% if suggested < 255 %}
          {{ suggested }}
         {% else %}
          255
         {% endif %}
#######
- alias: kamerhildelicht_dim_down_hold
#  hide_entity: true
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kamerhildedimmer
        event: 2001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kamerhildelicht
        transition: '5'
        brightness: >
         {% set suggested = states.light.kamerhildelicht.attributes.brightness|int - 80 %}
         {% if suggested > 25 %}
          {{ suggested }}
         {% else %}
          25
         {% endif %} 
#######
- alias: kamerhildelicht_dim_stop_hold
#  hide_entity: true
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kamerhildedimmer
        event: 1003
    - platform: event
      event_type: deconz_event
      event_data:
        id: kamerhildedimmer
        event: 2003
  action:         
    - service: light.turn_on
      data_template:
        entity_id: light.kamerhildelicht
        brightness: '{{ states.light.kamerhildelicht.attributes.brightness }}'